package matchtracker;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * Brendan Waters
 * brenardo9956@gmail.com
 */
public class Main extends javax.swing.JFrame {
    
    /**
     * Constants
     */
    
    //heroes
    static final String MAGE = "mage";
    static final String WARRIOR = "warrior";
    static final String ROGUE = "rogue";
    static final String PRIEST = "priest";
    static final String WARLOCK = "warlock";
    static final String SHAMAN = "shaman";
    static final String DRUID = "druid";
    static final String PALADIN = "paladin";
    static final String HUNTER = "hunter";
    static final List<String> HEROES = Arrays.asList(MAGE, WARRIOR, ROGUE, PRIEST, WARLOCK, SHAMAN, DRUID, PALADIN, HUNTER);
    
    //archetypes
    static final String AGGRO = "aggro";
    static final String TEMPO = "tempo";
    static final String CONTROL = "control";
    static final String COMBO = "combo";
    static final String MIDRANGE = "midrange";
    static final String RAMP = "ramp";
    static final List<String> ARCHETYPES = Arrays.asList(AGGRO, TEMPO, CONTROL, COMBO, MIDRANGE, RAMP);
    
    //outcomes
    static final String WIN = "win";
    static final String LOSS = "loss";
    static final List<String> OUTCOMES = Arrays.asList(WIN, LOSS);
    
    //filename
    static final String FILEPATH = "data/data.txt";
    
    /**
     * Fields
     */
    static ArrayList<Match> matches = new ArrayList();

    /**
     * Creates new form Menu
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        //set actions of buttons
        EnterListener el = new EnterListener(this);
        enterButton.addActionListener(el);
        QueryListener ql = new QueryListener(this);
        queryButton.addActionListener(ql);
        
        //load past matches
        LoadFile();
        
    }
    
    private void LoadFile(){
        
        try {
            
            FileReader file = new FileReader(FILEPATH);
            BufferedReader reader = new BufferedReader(file);
            String line;
            
            while((line = reader.readLine()) != null){
                
                Match match = new Match();
                
                //get each token out of each line
                Scanner scanner = new Scanner(line);
                scanner.useDelimiter(" ");
                if(scanner.hasNext()){
                    match.SetHero(scanner.next());
                    match.SetArchetype(scanner.next());
                    match.SetOpHero(scanner.next());
                    match.SetOpArchetype(scanner.next());
                    match.setOutcome(scanner.next());
                }
                
                matches.add(match);
                
            }
            
            reader.close();
            
        } catch (FileNotFoundException ex) {
            
            //file wasn't found, so make it
            File file = new File(FILEPATH);
            try{
                file.createNewFile();
            }catch(IOException fileEx){
                JOptionPane.showMessageDialog(null, fileEx.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch(IOException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error loading match", "Error", JOptionPane.ERROR_MESSAGE);
        }
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        enterButton = new java.awt.Button();
        queryButton = new java.awt.Button();
        label1 = new java.awt.Label();
        infoButton = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Match Tracker");
        setMaximumSize(new java.awt.Dimension(250, 150));
        setMinimumSize(new java.awt.Dimension(250, 150));

        jPanel1.setPreferredSize(new java.awt.Dimension(250, 150));

        enterButton.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        enterButton.setLabel("Enter Match");

        queryButton.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        queryButton.setLabel("Query Data");

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        label1.setText("Menu");

        infoButton.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        infoButton.setLabel("Information");
        infoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(queryButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(infoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(queryButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(infoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoButtonActionPerformed
     
        String message = "Valid Heroes:\n"
                + "\"Mage\", \"Druid\", \"Shaman\",\n"
                + "\"Priest\", \"Rogue\", \"Hunter\",\n"
                + "\"Paladin\", \"Warrior\", \"Warlock\"\n"
                + "\n"
                + "Valid Archetypes:\n"
                + "\"Aggro\", \"Midrange\", \"Control\",\n"
                + "\"Tempo\", \"Ramp\", \"Combo\"\n"
                + "\n"
                + "Valid Outcomes:\n"
                + "\"Win\", \"Loss\"\n"
                + "\n"
                + "Created by Brendan Waters 2015\n"
                + "Email: brenardo9956@gmail.com";
        
        JOptionPane.showMessageDialog(this, message, "Information", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_infoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        new Main().setVisible(true);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button enterButton;
    private java.awt.Button infoButton;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Button queryButton;
    // End of variables declaration//GEN-END:variables
}
