package matchtracker;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * Brendan Waters
 * brenardo9956@gmail.com
 */
public class MatchFrame extends javax.swing.JFrame {
    
    JFrame mainFrame;
    
    /**
     * Creates new form MatchFrame
     */
    public MatchFrame(JFrame m) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        mainFrame = m;
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        heroField = new javax.swing.JTextField();
        archField = new javax.swing.JTextField();
        enterButton = new java.awt.Button();
        opHeroField = new javax.swing.JTextField();
        opArchField = new javax.swing.JTextField();
        outcomeField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Match Tracker");
        setMaximumSize(new java.awt.Dimension(250, 200));
        setMinimumSize(new java.awt.Dimension(250, 200));

        jPanel1.setMaximumSize(new java.awt.Dimension(250, 150));
        jPanel1.setMinimumSize(new java.awt.Dimension(250, 150));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 150));

        heroField.setText("Hero");
        heroField.setMinimumSize(new java.awt.Dimension(100, 20));
        heroField.setPreferredSize(new java.awt.Dimension(200, 20));

        archField.setText("Archetype");
        archField.setPreferredSize(new java.awt.Dimension(200, 20));
        archField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                archFieldFocusGained(evt);
            }
        });

        enterButton.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        enterButton.setLabel("Enter");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        opHeroField.setText("Opponent Hero");
        opHeroField.setPreferredSize(new java.awt.Dimension(200, 20));
        opHeroField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                opHeroFieldFocusGained(evt);
            }
        });

        opArchField.setText("Opponent Archetype");
        opArchField.setPreferredSize(new java.awt.Dimension(200, 20));
        opArchField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                opArchFieldFocusGained(evt);
            }
        });

        outcomeField.setText("Outcome");
        outcomeField.setPreferredSize(new java.awt.Dimension(200, 20));
        outcomeField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                outcomeFieldFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(outcomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opArchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opHeroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(archField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(96, 96, 96)
                            .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(heroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(heroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(archField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opHeroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opArchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outcomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        heroField.getAccessibleContext().setAccessibleName("");
        archField.getAccessibleContext().setAccessibleName("Archetype");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        
        //create new match to enter data into
        Match match = new Match();
        
        //enforce entering correct data
        try{
            //set match data
            match.SetHero(heroField.getText());
            match.SetArchetype(archField.getText());
            match.SetOpHero(opHeroField.getText());
            match.SetOpArchetype(opArchField.getText());
            match.setOutcome(outcomeField.getText());
        
            //save match data and add to current list
            match.WriteToFile();
            Main.matches.add(match);

            //close this window, go back to main frame
            this.dispose();
            mainFrame.setVisible(true);
        }catch(Exception ex){
    
            //some field was invalid
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            
        }
        
    }//GEN-LAST:event_enterButtonActionPerformed

    private void outcomeFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_outcomeFieldFocusGained
        outcomeField.setText(null);
    }//GEN-LAST:event_outcomeFieldFocusGained

    private void opArchFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_opArchFieldFocusGained
        opArchField.setText(null);
    }//GEN-LAST:event_opArchFieldFocusGained

    private void opHeroFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_opHeroFieldFocusGained
        opHeroField.setText(null);
    }//GEN-LAST:event_opHeroFieldFocusGained

    private void archFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_archFieldFocusGained
        archField.setText(null);
    }//GEN-LAST:event_archFieldFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField archField;
    private java.awt.Button enterButton;
    private javax.swing.JTextField heroField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField opArchField;
    private javax.swing.JTextField opHeroField;
    private javax.swing.JTextField outcomeField;
    // End of variables declaration//GEN-END:variables
}
