/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package matchtracker;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Owner
 */
public class QueryFrame extends javax.swing.JFrame {
    
    JFrame mainFrame;

    /**
     * Creates new form QueryFrame
     */
    public QueryFrame(JFrame m) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        mainFrame = m;
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exitButton = new javax.swing.JLabel();
        heroField = new javax.swing.JTextField();
        archField = new javax.swing.JTextField();
        opHeroField = new javax.swing.JTextField();
        opArchField = new javax.swing.JTextField();
        searchButton = new java.awt.Button();
        button1 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(250, 180));
        setMinimumSize(new java.awt.Dimension(250, 180));

        exitButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        exitButton.setText("Choose Search Parameters");

        heroField.setText("Hero");
        heroField.setMinimumSize(new java.awt.Dimension(200, 20));
        heroField.setPreferredSize(new java.awt.Dimension(200, 20));

        archField.setText("Archetype");
        archField.setPreferredSize(new java.awt.Dimension(200, 20));
        archField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                archFieldFocusGained(evt);
            }
        });

        opHeroField.setText("Opponent Hero");
        opHeroField.setPreferredSize(new java.awt.Dimension(200, 20));
        opHeroField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                opHeroFieldFocusGained(evt);
            }
        });

        opArchField.setText("Opponent Archetype");
        opArchField.setPreferredSize(new java.awt.Dimension(200, 20));
        opArchField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                opArchFieldFocusGained(evt);
            }
        });

        searchButton.setActionCommand("");
        searchButton.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        searchButton.setLabel("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        button1.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        button1.setLabel("Exit");
        button1.setPreferredSize(new java.awt.Dimension(59, 23));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(heroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(archField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(opHeroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(opArchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(exitButton)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(exitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(heroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(archField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opHeroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opArchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        
        //get search parameters
        String hero = heroField.getText().toLowerCase();
        if(!Main.HEROES.contains(hero)){
            hero = null;
        }
        String archetype = archField.getText().toLowerCase();
        if(!Main.ARCHETYPES.contains(archetype)){
            archetype = null;
        }
        String opHero = opHeroField.getText().toLowerCase();
        if(!Main.HEROES.contains(opHero)){
            opHero = null;
        }
        String opArchetype = opArchField.getText().toLowerCase();
        if(!Main.ARCHETYPES.contains(opArchetype)){
            opArchetype = null;
        }
        
        //find matches with these parameters
        //keep track of wins & losses
        int wins = 0;
        int losses = 0;
        for(int i = 0; i < Main.matches.size(); i++){
            
            Match thisMatch = Main.matches.get(i);
            
            //check match against params
            boolean heroMatch = false;
            boolean archMatch = false;
            boolean opHeroMatch = false;
            boolean opArchMatch = false;
            if(hero == null || hero.equals(thisMatch.getHero())){
                heroMatch = true;
            }
            if(archetype == null || archetype.equals(thisMatch.getArchetype())){
                archMatch = true;
            }
            if(opHero == null || opHero.equals(thisMatch.getOpHero())){
                opHeroMatch = true;
            }
            if(opArchetype == null || opArchetype.equals(thisMatch.getOpArchetype())){
                opArchMatch = true;
            }
            
            //if theyre all true, then this match fits params
            if(heroMatch && archMatch && opHeroMatch && opArchMatch){
                
                //count the win or loss
                switch (thisMatch.getOutcome()) {
                    case Main.WIN:
                        wins++;
                        break;
                    case Main.LOSS:
                        losses++;
                        break;
                }
                
            }          
            
        }
        
        //calculate win/loss ratio
        double ratio;
        ratio = 100 * ((double)wins / (double)(wins + losses));
        
        //show results to user
        NumberFormat formatter = new DecimalFormat("#0.00"); 
        String results = "Total Wins: " + wins + "\n"
                + "Total Losses: " + losses + "\n"
                + "Win/Loss Ratio: " + formatter.format(ratio) + "%";
        JOptionPane.showMessageDialog(this, results, "Results", JOptionPane.PLAIN_MESSAGE);
        
    }//GEN-LAST:event_searchButtonActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        
        //close this window, go back to main frame
        this.dispose();
        mainFrame.setVisible(true);
        
    }//GEN-LAST:event_button1ActionPerformed

    private void archFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_archFieldFocusGained
        archField.setText(null);
    }//GEN-LAST:event_archFieldFocusGained

    private void opHeroFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_opHeroFieldFocusGained
        opHeroField.setText(null);
    }//GEN-LAST:event_opHeroFieldFocusGained

    private void opArchFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_opArchFieldFocusGained
        opArchField.setText(null);
    }//GEN-LAST:event_opArchFieldFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField archField;
    private java.awt.Button button1;
    private javax.swing.JLabel exitButton;
    private javax.swing.JTextField heroField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField opArchField;
    private javax.swing.JTextField opHeroField;
    private java.awt.Button searchButton;
    // End of variables declaration//GEN-END:variables
}
